Lonia:
  Name: Lonia
  Color: '&6'
  Autobans: true
  Ban-Command: /ban %player% Cheating
  Debug-Mode: false
Checks:
  Fly-A:
    enabled: true
    autoban: true
  Fly-B:
    enabled: true
    autoban: true
  Fly-C:
    enabled: true
    autoban: true
  Fly-D:
    enabled: true
    autoban: true
  Fly-E:
    enabled: true
    autoban: true
data:
  toggled-player-alerts: []
  exempt-players: []